    const motivos = [
            { "motivo": "Ato de desídia: registro de ponto sem a devida presença no local de trabalho ou atendimento designado." },
            { "motivo": "Ato de Indisciplina – Por ausência de batidas e falta de comprometimento nas solicitações de ponto." },
            { "motivo": "Ato de Indisciplina – Por falta de atenção recorrente ao não realizar marcações de ponto e solicitações constantes de ajuste de ponto." },
            { "motivo": "Descumprimento do horário de intervalo, realizando pausas superiores ao limite estabelecido pela empresa." },
            { "motivo": "Descumprimento do horário de intervalo, realizando pausas superiores ao limite estabelecido pela empresa. Foi identificado que o colaborador registrou o retorno do intervalo no relógio de ponto, contudo não retomou as atividades laborais, em desacordo com as normas internas da empresa." },
            { "motivo": "Manter a janela aberta por período superior a 15 minutos após o intervalo de almoço, não iniciando o contrato subsequente dentro do prazo estabelecido." },
            { "motivo": "Falta sem justificativa no dia." },
            { "motivo": "Faltas consecutivas sem justificativa nos dias." },
            { "motivo": "Ausência parcial do expediente sem justificativa legal, apresentando apenas atestado de horas, que não abrangeu todo o período da falta." },
            { "motivo": "Por chegar atrasado, sem apresentar justificativa." },
            { "motivo": "Ausentou-se para o intervalo de almoço e não retornou ao posto de trabalho, caracterizando abandono de função no período e descumprimento da jornada estabelecida." },
            { "motivo": "Por não comparecer à reunião convocada pela supervisão." },
            { "motivo": "Conduta inadequada que compromete a comunicação e o desempenho das atividades profissionais." },
            { "motivo": "Conduta inadequada - Por ter adotado postura inadequada durante reunião interna, elevando o tom de voz e discutindo de forma incompatível com o ambiente profissional, diante dos demais colaboradores." },
            { "motivo": "Desrespeito: comportamento inadequado ou falta de respeito com outro colaborador, alterando o tom ou gerando discussão." },
            { "motivo": "Insubordinação." },
            { "motivo": "Insubordinação: recusa em cumprir atividade ou orientação determinada pela liderança." },
            { "motivo": "Utilização de aparelho celular durante o horário de trabalho sem justificativa ou relação com as atividades." },
            { "motivo": "Ato desídia, por assinar um documento digital se passando pelo cliente." },
            { "motivo": "Ato desídia, por manipular o sistema de batida de ponto." },
            { "motivo": "Desídia - Prestou informação falsa para não realizar a troca de equipamento do cliente." },
            { "motivo": "Má conduta – desvio de material." },
            { "motivo": "Registro de informações inverídicas no formulário de validação de serviço, em desacordo com os procedimentos internos, comprometendo a confiabilidade dos controles internos e a integridade dos processos da empresa." },
            { "motivo": "Descumprimento imotivado do serviço." },
            { "motivo": "Abandono de rota, sem comunicação prévia à liderança e sem justificativa." },
            { "motivo": "Não cumprir com os procedimentos da empresa, orientando o cliente a reagendar o serviço por meio do aplicativo Minha Claro, em desacordo com os procedimentos estabelecidos pela empresa." },
            { "motivo": "Conduta inadequada ao cancelar revisita de forma indevida, com o objetivo de não impactar os indicadores de desempenho. Tal prática caracteriza descumprimento aos procedimentos da empresa." },
            { "motivo": "Não cumprir com os procedimentos da empresa, não realizando a unificação das redes de Wi-Fi, deixando o serviço com percentual de conclusão abaixo do exigido." },
            { "motivo": "Não cumprir com os procedimentos da empresa, instalação fora do padrão. Durante autoinspeção do Controle de Qualidade da Claro, foi constatado que o colaborador não realizou a instalação da capinha do mini isolador." },
            { "motivo": "Não cumprir com os procedimentos da empresa, instalação fora do padrão. Foi constatada a execução de adesão utilizando cabeamento (fibra) pertencente a outra operadora, prática que não está em conformidade com os procedimentos técnicos e normas internas da empresa." },
            { "motivo": "Não cumprir com os procedimentos da empresa, instalação fora do padrão. Durante autoinspeção do Controle de Qualidade da Claro, foi constatado que o colaborador deixou de colher a assinatura do cliente na ordem de serviço." },
            { "motivo": "Não cumprir com os procedimentos da empresa, instalação fora do padrão, deixando o cabo DROP com emenda, prática não permitida, ocasionando retorno de serviço." },
            { "motivo": "Não cumprir com os procedimentos da empresa, foto de evidência fora do padrão." },
            { "motivo": "Não cumprir com os procedimentos da empresa, foto de evidência fora do padrão. Durante inspeção do controle de qualidade da Claro, foi constatado que a foto registrada pelo colaborador estava fora do padrão exigido, não apresentando de forma adequada o conector e a ONT, conforme orientações." },
            { "motivo": "Não cumprir com os procedimentos da empresa, realizando lançamento indevido de material." },
            { "motivo": "Não cumprir com os procedimentos da empresa, realizando baixa indevida, sem validação com seu superior." },
            { "motivo": "Não cumprir com os procedimentos da empresa, realizando baixa sem validação com seu superior." },
            { "motivo": "Não cumprir com os procedimentos do setor do almoxarifado, entregando material restrito, sem autorização do seu superior." },
            { "motivo": "Não cumprir com os procedimentos da empresa, não realizando o lançamento de material." },
            { "motivo": "Não cumprir com os procedimentos da empresa, não realizando processo do NR35." },
            { "motivo": "Por não utilizar o Equipamento de Proteção Individual (E.P.I.) durante o desempenho de suas atividades, contrariando as normas de segurança do trabalho da empresa." },
            { "motivo": "Utilização de veículo fora do horário de trabalho." },
            { "motivo": "Por não realizar o lançamento do atestado médico no aplicativo da empresa, conforme procedimento interno." },
            { "motivo": "Não cumprir com os procedimentos da empresa, não realizando validação do quality da manutenção com seu superior ou COP." },
            { "motivo": "Não cumprir com os procedimentos da empresa, não inserindo as evidências no Connect." },
            { "motivo": "Não cumprir os procedimentos da empresa, inserindo evidências de forma incorreta no Connect." },
            { "motivo": "Não cumprir com os procedimentos da empresa, uma vez que o colaborador não efetuou o envio das informações obrigatórias no sistema CONECT, incluindo foto com geolocalização, fotos dos ativos e registro da baixa." },
            { "motivo": "Não cumprir com os procedimentos da empresa, afetando indicador. Colaborador realizou a baixa da O.S. fora da grade, ocasionando impacto negativo no indicador TEC1." },
            { "motivo": "Não cumprir com os procedimentos da empresa, não realizando o monitoramento da rota, afetando indicador TEC1." },
            { "motivo": "Por iniciar o primeiro atendimento após as 08h30, afetando indicador." }
    ]
export default motivos;